[unstable]
build-std = ["core", "compiler_builtins"]

# [target.arm-raspirus_os]
# linker = "arm-none-eabi-gcc"

# [target.armv7r-unknown-none]
# linker = "arm-none-eabi-gcc"

[target.arm-none-eabi]
linker = "arm-none-eabi-gcc"